apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
  clusterIP: None
  selector:
    app: redis

# # No need for apps before v1, since services are part core modules
# apiVersion: v1
# kind: Service
# metadata:
#   name: redis-service
# spec:
#   # Select pods, with key-value pair, by default and only possiblity is to select with labels
#   selector:
#     app: redis
#   ports:
#     #Array of ports can be declared here, thus we need "-" for each of the port
#     - protocol: 'TCP'
#       port: 6379
#       targetPort: 6379
#   type: LoadBalancer